Controllers/AppointmentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Agenda.Models;
using System.Text.RegularExpressions; // Pour utilisation des regex

namespace Agenda.Controllers
{
    public class AppointmentsController : Controller
    {
        private AgendaEntities db = new AgendaEntities();
        // Liste des RDV
        public ActionResult AppointmentList()
        {
            var appointments = db.Appointments.Include(a => a.Broker).Include(a => a.Customer);
            return View(appointments.ToList());
        }
        // Détail RDV
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Appointment appointment = db.Appointments.Find(id);
            if (appointment == null)
            {
                return RedirectToAction("Error", "Error");
            }
            return View(appointment);
        }
        // Création I RDV
        public ActionResult addAppointment(int? id)
        {
            if (id == null)
            {
                ViewBag.idBroker = new SelectList(db.Brokers, "idBroker", "LastName");
                ViewBag.idCustomer = new SelectList(db.Customers, "idCustomer", "LastName");
                return View();
            }
            else
            {
                ViewBag.idBroker = new SelectList(db.Brokers, "idBroker", "LastName",id);
                ViewBag.idCustomer = new SelectList(db.Customers, "idCustomer", "LastName");
                return View();
            }
        }
        // Création II RDV
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult addAppointment([Bind(Include = "idAppointment,DateHour,idBroker,idCustomer")] Appointment appointment)
        {
            ViewBag.idBroker = new SelectList(db.Brokers, "idBroker", "LastName", appointment.idBroker);
            ViewBag.idCustomer = new SelectList(db.Customers, "idCustomer", "LastName", appointment.idCustomer);
            Appointment test = db.Appointments.Where(x => x.idBroker == appointment.idBroker && x.DateHour == appointment.DateHour).FirstOrDefault();
            if (test == null) // Test si un courtier a déjà un rendez-vous !
            {
                if (ModelState.IsValid)
                {
                db.Appointments.Add(appointment);
                db.SaveChanges();
                return RedirectToAction("AppointmentList");
                }
                else
                {
                return View(appointment);
                }
            }
            else
            {
            return View("Already");
            }
        }
        // Edition I RDV
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Appointment appointment = db.Appointments.Find(id);
            if (appointment == null)
            {
                return RedirectToAction("Error", "Error");
            }
            ViewBag.idBroker = new SelectList(db.Brokers, "idBroker", "LastName", appointment.idBroker);
            ViewBag.idCustomer = new SelectList(db.Customers, "idCustomer", "LastName", appointment.idCustomer);
            return View(appointment);
        }
        // Edition II RDV
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "idAppointment,DateHour,idBroker,idCustomer")] Appointment appointment)
        {
            if (ModelState.IsValid)
            {
                db.Entry(appointment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("AppointmentList");
            }
            ViewBag.idBroker = new SelectList(db.Brokers, "idBroker", "LastName", appointment.idBroker);
            ViewBag.idCustomer = new SelectList(db.Customers, "idCustomer", "LastName", appointment.idCustomer);
            return View(appointment);
        }
        // Suppression I RDV
        public ActionResult DelApp(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Appointment delapp = db.Appointments.Find(id);
            if (delapp == null)
            {
                return RedirectToAction("Error", "Error");
            }
            return View(delapp);
        }
        // Suppression II RDV
        [HttpPost, ActionName("DelApp")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Appointment delapp = db.Appointments.Find(id);
            db.Appointments.Remove(delapp);
            db.SaveChanges();
            return RedirectToAction("AppointmentList");
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/BrokerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using System.Data.Entity.Validation;
using Agenda.Models;
using System.Text.RegularExpressions; // Pour utilisation des regex

namespace Agenda.Controllers
{
    public class BrokerController : Controller
    {
        private AgendaEntities db = new AgendaEntities();
        // Page ajouter courtier
        public ActionResult addBroker()
        {
            return View("addBroker");
        }
        // Page de succès
        public ActionResult Success()
        {
            return View("Success");
        }
        // Page de succès MAJ courtier
        public ActionResult Maj()
        {
            return View("Maj");
        }
        // Add A New Broker
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult addBroker([Bind(Include = "idBroker,LastName,FirstName,Mail,PhoneNumber")] Broker broker)
        {
            //Déclaration des regex
            string regexName = @"^[A-Za-zéèàêâôûùïüç\-]+$";
            string regexMail = @"[0-9a-zA-Z\.\-]+@[0-9a-zA-Z\.\-]+.[a-zA-Z]{2,4}";
            string regexPhone = @"^[0][0-9]{9}";

            //Vérification que le champ lastname n'est pas null ou vide
            if (!String.IsNullOrEmpty(broker.LastName)) //si le champ lastname n'est pas vide ou null on vérifie la validité de l'entrée
            {
                //Vérification de la validité de l'entrée
                if (!Regex.IsMatch(broker.LastName, regexName)) //si l'entrée utilisateur ne passe pas la regex ajout d'un message d'erreur
                {
                    //Message d'erreur
                    ModelState.AddModelError("LastName", "Veuillez écrire un nom valide");
                }
            }
            else
            {
                //Message d'erreur si le champ lastname est vide ou null
                ModelState.AddModelError("LastName", "Veuillez écrire un nom");
            }
            //Vérification que le champ firstname n'est pas null ou vide
            if (!String.IsNullOrEmpty(broker.FirstName))
            {
                //Vérification de la validité de l'entrée
                if (!Regex.IsMatch(broker.FirstName, regexName))
                {
                    //Message d'erreur
                    ModelState.AddModelError("FirstName", "Veuillez écrire un prénom valide");
                }
            }
            else
            {
                //Message d'erreur
                ModelState.AddModelError("FirstName", "Veuillez écrire un prénom");
            }
            //Vérification que le champ mail n'est pas null ou vide
            if (!String.IsNullOrEmpty(broker.Mail))
            {
                //Vérification de la validité de l'entrée
                if (!Regex.IsMatch(broker.Mail, regexMail))
                {
                    //Message d'erreur
                    ModelState.AddModelError("Mail", "Veuillez écrire un mail valide");
                }
            }
            else
            {
                //Message d'erreur
                ModelState.AddModelError("Mail", "Veuillez écrire un mail");
            }
            //Vérification que le champ phoneNumber n'est pas null ou vide
            if (!String.IsNullOrEmpty(broker.PhoneNumber))
            {
                //Vérification de la validité de l'entrée
                if (!Regex.IsMatch(broker.PhoneNumber, regexPhone))
                {
                    //Message d'erreur
                    ModelState.AddModelError("PhoneNumber", "Veuillez écrire un téléphone valide");
                }
            }
            else
            {
                //Message d'erreur
                ModelState.AddModelError("PhoneNumber", "Veuillez renseigner un numéro de téléphone");
            }

            //si il n'y a pas d'erreur
            if (ModelState.IsValid)
            {
                db.Brokers.Add(broker); //insertion dans base
                db.SaveChanges(); //enregistrement des changements
                return RedirectToAction("Success"); //redirection vers la page SuccessAddBroker
            }
            else
            {
                return View(broker); //s'il y a des erreurs réaffichage du formulaire
            }
        }
        //Liste des courtiers
        public ActionResult ListBrokers()
        {
            return View(db.Brokers.ToList());
        }
        // Détails courtier
        public ActionResult profilBroker(int id) // int? entier qui peux être nul !
        {
            Broker broker = db.Brokers.Find(id);
            if (broker == null)
            {
                return RedirectToAction("Error", "Error"); // Mettre une page d'erreur
            }
            return View(broker);
        }
        // Mise à jour courtier
        public ActionResult profileBroker(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Broker brokerup = db.Brokers.Find(id);
            if (brokerup == null)
            {
                return RedirectToAction("Error","Error");
            }
            return View(brokerup);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult profilBroker([Bind(Include = "idBroker,LastName,FirstName,Mail,PhoneNumber")] Broker brokerup)
        {
        //Déclaration des regex
        string regexName = @"^[A-Za-zéèàêâôûùïüç\-]+$";
            string regexMail = @"[0-9a-zA-Z\.\-]+@[0-9a-zA-Z\.\-]+.[a-zA-Z]{2,4}";
            string regexPhone = @"^[0][0-9]{9}";

            //Vérification que le champ lastname n'est pas null ou vide
            if (!String.IsNullOrEmpty(brokerup.LastName)) //si le champ lastname n'est pas vide ou null on vérifie la validité de l'entrée
            {
                //Vérification de la validité de l'entrée
                if (!Regex.IsMatch(brokerup.LastName, regexName)) //si l'entrée utilisateur ne passe pas la regex ajout d'un message d'erreur
                {
                    //Message d'erreur
                    ModelState.AddModelError("LastName", "Veuillez écrire un nom valide");
                }
            }
            else
            {
                //Message d'erreur si le champ lastname est vide ou null
                ModelState.AddModelError("LastName", "Veuillez écrire un nom");
            }
            //Vérification que le champ firstname n'est pas null ou vide
            if (!String.IsNullOrEmpty(brokerup.FirstName))
            {
                //Vérification de la validité de l'entrée
                if (!Regex.IsMatch(brokerup.FirstName, regexName))
                {
                    //Message d'erreur
                    ModelState.AddModelError("FirstName", "Veuillez écrire un prénom valide");
                }
            }
            else
            {
                //Message d'erreur
                ModelState.AddModelError("FirstName", "Veuillez écrire un prénom");
            }
            //Vérification que le champ mail n'est pas null ou vide
            if (!String.IsNullOrEmpty(brokerup.Mail))
            {
                //Vérification de la validité de l'entrée
                if (!Regex.IsMatch(brokerup.Mail, regexMail))
                {
                    //Message d'erreur
                    ModelState.AddModelError("Mail", "Veuillez écrire un mail valide");
                }
            }
            else
            {
                //Message d'erreur
                ModelState.AddModelError("Mail", "Veuillez écrire un mail");
            }
            //Vérification que le champ phoneNumber n'est pas null ou vide
            if (!String.IsNullOrEmpty(brokerup.PhoneNumber))
            {
                //Vérification de la validité de l'entrée
                if (!Regex.IsMatch(brokerup.PhoneNumber, regexPhone))
                {
                    //Message d'erreur
                    ModelState.AddModelError("PhoneNumber", "Veuillez écrire un téléphone valide");
                }
            }
            else
            {
                //Message d'erreur
                ModelState.AddModelError("PhoneNumber", "Veuillez renseigner un numéro de téléphone");
            }

            //si il n'y a pas d'erreur
            if (ModelState.IsValid)
            {
                db.Entry(brokerup).State = EntityState.Modified;//Mise à jour
                db.SaveChanges(); //enregistrement des changements
                return RedirectToAction("Maj"); //redirection vers la page Maj
            }
            else
            {
                return View(brokerup); //s'il y a des erreurs réaffichage du formulaire
            }
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Agenda</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/assets/css/style.css" rel="stylesheet" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body onload="startTime()">
    @*HAUT DE PAGE HEADER*@
    <header>
        <nav class="navbar navbar-expand-sm bg-transparent navbar-dark fixed-top" id="navi">
            <!--Bouton collapse-->
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#coll">
                <span class="navbar-toggler-icon"></span>
            </button>
            <!--Liens de la navbar-->
            <div class="collapse navbar-collapse" id="coll">
                <ul class="navbar-nav m-auto p-1">
                    <li class="nav-item active">
                        <a class="nav-link" href="#">@Html.ActionLink("Accueil", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="#">@Html.ActionLink("Liste Courtiers", "ListBrokers", "Broker", new { area = "" }, new { @class = "nav-link" })</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="#">@Html.ActionLink("Liste Clients", "ListCustomers", "Customer", new { area = "" }, new { @class = "nav-link" })</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="#">@Html.ActionLink("Pagination Clients", "Pagination", "Customer", new { area = "" }, new { @class = "nav-link" })</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="#">@Html.ActionLink("Nouveau Courtier", "addBroker", "Broker", new { area = "" }, new { @class = "nav-link" })</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="#">@Html.ActionLink("Nouveau Client", "addCustomer", "Customer", new { area = "" }, new { @class = "nav-link" })</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="#">@Html.ActionLink("Liste Rendez-Vous", "AppointmentList", "Appointments", new { area = "" }, new { @class = "nav-link" })</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="#">@Html.ActionLink("Nouveau Rendez-Vous", "addAppointment", "Appointments", new { area = "" }, new { @class = "nav-link" })</a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    @*BODY*@
    <div class="RB">@RenderBody()</div>
    @*BAS DE PAGE FOOTER*@
    <footer class="fixed-bottom bg-info">
        @*<div class="flex">
                <ul class="breadcrumb">
                    <li class="breadcrumb-item"><a href="/Broker/ListBrokers">Liste Courtiers</a></li>
                    <li class="breadcrumb-item"><a href="/Customer/ListCustomers">Liste Clients</a></li>
                    <li class="breadcrumb-item"><a href="/Broker/addBroker">Nouveau Courtier</a></li>
                    <li class="breadcrumb-item"><a href="/Customer/addCustomer">Nouveau Client</a></li>
                    <li class="breadcrumb-item"><a href="/Appointments/AppointmentList">Liste Rendez-Vous</a></li>
                    <li class="breadcrumb-item"><a href="/Appointments/addAppointment">Nouveau Rendez-Vous</a></li>
                    <li class="breadcrumb-item"><a href="/Appointments/DelAppointment">Supprimer Rendez-Vous</a></li>
                </ul>
            </div>*@
        <div class="d-flex flex-row justify-content-center">
            <div class="flex p-2 bg-info text-light" id="date"></div>
            @*<div class="flex p-2 bg-info text-light" id="time"></div>*@
            <div class="flex p-2 bg-info" id="txt"></div>
        </div>
    </footer>
    @*SCRIPTS*@
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/umd/popper.min.js"></script>
    <script src="~/assets/js/Time.js"></script>
    <script src="~/assets/js/Realtime.js"></script>
</body>
</html>